name: Docker Build

# This workflow usea actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*'
  schedule:
    - cron: '0 2 * * *'  # every day at 2:00 UTC
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: goldbricklemon/tonie-podcast-sync
  TPS_VERSIONS: '["3.3.2", "3.3.3", "main"]'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        tps_version: [ "3.3.2", "3.3.3", "main" ]
        variant:
          - name: default
            image_suffix: ""
            buildargs: ""
          - name: noffmpeg
            image_suffix: "-noffmpeg"
            buildargs: "INCLUDE_FFMPEG=false"

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set latest tps version
        id: set-latest-tps
        run: |
          versions=$(echo '${{ env.TPS_VERSIONS }}' | jq -r '.[]' | grep -v main | sort -V)
          latest=$(echo "$versions" | tail -n1)
          echo "LATEST_TPS_VERSION=$latest" >> $GITHUB_ENV

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      #- name: Install cosign
      #  if: github.event_name != 'pull_request'
      #  uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
      #  with:
      #    cosign-release: 'v2.2.4'


      # Setup QEMU for multi-arch build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Decide on image tags based on event type and TPS version
      # Build for tps releases on tag pushes (+ latest alias)
      # Build for tps main on main branch pushes and scheduled runs (nightly)
      - name: Set image tags
        id: set-tags
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" =~ refs/tags/v && "${{ matrix.tps_version }}" != "main" ]]; then
            TAG="${{ matrix.tps_version }}${{ matrix.variant.image_suffix }}"
            if [[ "${{ matrix.tps_version }}" == "$LATEST_TPS_VERSION" ]]; then
              LATEST_TAG="latest${{ matrix.variant.image_suffix }}"
              LATEST_ENABLED=true
            else
              LATEST_TAG=""
              LATEST_ENABLED=false
            fi
            echo "DEBUG TAG: $TAG"
            echo "DEBUG LATET_TAG: $LATEST_TAG"
          elif ([[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]] || [[ "${{ github.event_name }}" == "schedule" ]]) && [[ "${{ matrix.tps_version }}" == "main" ]]; then
            TAG="nightly${{ matrix.variant.image_suffix }}"
            LATEST_TAG=""
            LATEST_ENABLED=false
          else
            TAG=""
            LATEST_TAG=""
            LATEST_ENABLED=false
          fi
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "LATEST_ENABLED=$LATEST_ENABLED" >> $GITHUB_OUTPUT

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.set-tags.outputs.TAG }}
            type=raw,enabled=${{ steps.set-tags.outputs.LATEST_ENABLED }},value=${{ steps.set-tags.outputs.LATEST_TAG }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        if: |
          (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && matrix.tps_version != 'main') ||
          ((github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'schedule') && matrix.tps_version == 'main'
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          build-args: |
            TPS_VERSION=${{ matrix.tps_version }}
            ${{ matrix.variant.buildargs }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      #- name: Sign the published Docker image
      #  if: ${{ github.event_name != 'pull_request' }}
      #  env:
      #    # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
      #    TAGS: ${{ steps.meta.outputs.tags }}
      #    DIGEST: ${{ steps.build-and-push.outputs.digest }}
      #  # This step uses the identity token to provision an ephemeral certificate
      #  # against the sigstore community Fulcio instance.
      #  run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
